// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: internal/protos/cellpose.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CellposeService_ProcessImage_FullMethodName = "/cellpose.CellposeService/ProcessImage"
)

// CellposeServiceClient is the client API for CellposeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CellposeServiceClient interface {
	ProcessImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageResponse, error)
}

type cellposeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCellposeServiceClient(cc grpc.ClientConnInterface) CellposeServiceClient {
	return &cellposeServiceClient{cc}
}

func (c *cellposeServiceClient) ProcessImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageResponse)
	err := c.cc.Invoke(ctx, CellposeService_ProcessImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CellposeServiceServer is the server API for CellposeService service.
// All implementations must embed UnimplementedCellposeServiceServer
// for forward compatibility.
type CellposeServiceServer interface {
	ProcessImage(context.Context, *ImageRequest) (*ImageResponse, error)
	mustEmbedUnimplementedCellposeServiceServer()
}

// UnimplementedCellposeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCellposeServiceServer struct{}

func (UnimplementedCellposeServiceServer) ProcessImage(context.Context, *ImageRequest) (*ImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessImage not implemented")
}
func (UnimplementedCellposeServiceServer) mustEmbedUnimplementedCellposeServiceServer() {}
func (UnimplementedCellposeServiceServer) testEmbeddedByValue()                         {}

// UnsafeCellposeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CellposeServiceServer will
// result in compilation errors.
type UnsafeCellposeServiceServer interface {
	mustEmbedUnimplementedCellposeServiceServer()
}

func RegisterCellposeServiceServer(s grpc.ServiceRegistrar, srv CellposeServiceServer) {
	// If the following call pancis, it indicates UnimplementedCellposeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CellposeService_ServiceDesc, srv)
}

func _CellposeService_ProcessImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellposeServiceServer).ProcessImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellposeService_ProcessImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellposeServiceServer).ProcessImage(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CellposeService_ServiceDesc is the grpc.ServiceDesc for CellposeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CellposeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cellpose.CellposeService",
	HandlerType: (*CellposeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessImage",
			Handler:    _CellposeService_ProcessImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/protos/cellpose.proto",
}
