# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/cellpose.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/cellpose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/cellpose.proto\x12\x08\x63\x65llpose\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\x1d\n\x05Point\x12\t\n\x01y\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\"*\n\x07Outline\x12\x1f\n\x06points\x18\x01 \x03(\x0b\x32\x0f.cellpose.Point\"\xb6\x02\n\x0b\x43\x65llFeature\x12\x0f\n\x07\x63\x65ll_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rea\x18\x02 \x01(\x02\x12\x11\n\tperimeter\x18\x03 \x01(\x02\x12\x13\n\x0b\x63ircularity\x18\x04 \x01(\x02\x12\x14\n\x0c\x65\x63\x63\x65ntricity\x18\x05 \x01(\x02\x12\x10\n\x08solidity\x18\x06 \x01(\x02\x12\x16\n\x0emean_intensity\x18\x07 \x01(\x02\x12\x15\n\rmax_intensity\x18\x08 \x01(\x02\x12\x15\n\rmin_intensity\x18\t \x01(\x02\x12\x15\n\rintensity_std\x18\n \x01(\x02\x12\x18\n\x10texture_contrast\x18\x0b \x01(\x02\x12\x1f\n\x17nucleus_cytoplasm_ratio\x18\x0c \x01(\x02\x12 \n\x18is_potentially_malignant\x18\r \x01(\x08\"\x96\x02\n\rGlobalMetrics\x12\x13\n\x0btotal_cells\x18\x01 \x01(\x05\x12#\n\x1bpotentially_malignant_cells\x18\x02 \x01(\x05\x12\x1d\n\x15malignancy_percentage\x18\x03 \x01(\x02\x12\x1c\n\x14\x63\x65ll_density_per_mm2\x18\x04 \x01(\x02\x12\x16\n\x0emean_cell_size\x18\x05 \x01(\x02\x12\x1d\n\x15\x63\x65ll_size_variability\x18\x06 \x01(\x02\x12\x1b\n\x13mean_cell_intensity\x18\x07 \x01(\x02\x12\x1d\n\x15intensity_variability\x18\x08 \x01(\x02\x12\x1b\n\x13image_quality_score\x18\t \x01(\x02\"\xcf\x01\n\rImageResponse\x12#\n\x08outlines\x18\x01 \x03(\x0b\x32\x11.cellpose.Outline\x12\r\n\x05masks\x18\x02 \x03(\x05\x12\r\n\x05\x64iams\x18\x03 \x03(\x02\x12\x0e\n\x06styles\x18\x04 \x03(\x02\x12\x0c\n\x04rows\x18\x05 \x03(\x02\x12,\n\rcell_features\x18\x06 \x03(\x0b\x32\x15.cellpose.CellFeature\x12/\n\x0eglobal_metrics\x18\x07 \x01(\x0b\x32\x17.cellpose.GlobalMetrics2R\n\x0f\x43\x65llposeService\x12?\n\x0cProcessImage\x12\x16.cellpose.ImageRequest\x1a\x17.cellpose.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.cellpose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=35
  _globals['_IMAGEREQUEST']._serialized_end=69
  _globals['_POINT']._serialized_start=71
  _globals['_POINT']._serialized_end=100
  _globals['_OUTLINE']._serialized_start=102
  _globals['_OUTLINE']._serialized_end=144
  _globals['_CELLFEATURE']._serialized_start=147
  _globals['_CELLFEATURE']._serialized_end=457
  _globals['_GLOBALMETRICS']._serialized_start=460
  _globals['_GLOBALMETRICS']._serialized_end=738
  _globals['_IMAGERESPONSE']._serialized_start=741
  _globals['_IMAGERESPONSE']._serialized_end=948
  _globals['_CELLPOSESERVICE']._serialized_start=950
  _globals['_CELLPOSESERVICE']._serialized_end=1032
# @@protoc_insertion_point(module_scope)
