# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/cellpose.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/cellpose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/cellpose.proto\x12\x08\x63\x65llpose\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\x1d\n\x05Point\x12\t\n\x01y\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\"*\n\x07Outline\x12\x1f\n\x06points\x18\x01 \x03(\x0b\x32\x0f.cellpose.Point\"p\n\rImageResponse\x12#\n\x08outlines\x18\x01 \x03(\x0b\x32\x11.cellpose.Outline\x12\r\n\x05masks\x18\x02 \x03(\x05\x12\r\n\x05\x64iams\x18\x03 \x03(\x02\x12\x0e\n\x06styles\x18\x04 \x03(\x02\x12\x0c\n\x04rows\x18\x05 \x03(\x02\x32R\n\x0f\x43\x65llposeService\x12?\n\x0cProcessImage\x12\x16.cellpose.ImageRequest\x1a\x17.cellpose.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.cellpose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=35
  _globals['_IMAGEREQUEST']._serialized_end=69
  _globals['_POINT']._serialized_start=71
  _globals['_POINT']._serialized_end=100
  _globals['_OUTLINE']._serialized_start=102
  _globals['_OUTLINE']._serialized_end=144
  _globals['_IMAGERESPONSE']._serialized_start=146
  _globals['_IMAGERESPONSE']._serialized_end=258
  _globals['_CELLPOSESERVICE']._serialized_start=260
  _globals['_CELLPOSESERVICE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
