# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cellpose.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cellpose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x65llpose.proto\x12\x08\x63\x65llpose\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"K\n\rImageResponse\x12\r\n\x05masks\x18\x01 \x03(\x05\x12\r\n\x05\x64iams\x18\x02 \x03(\x02\x12\x0e\n\x06styles\x18\x03 \x03(\x02\x12\x0c\n\x04rows\x18\x04 \x03(\x02\x32R\n\x0f\x43\x65llposeService\x12?\n\x0cProcessImage\x12\x16.cellpose.ImageRequest\x1a\x17.cellpose.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cellpose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=28
  _globals['_IMAGEREQUEST']._serialized_end=62
  _globals['_IMAGERESPONSE']._serialized_start=64
  _globals['_IMAGERESPONSE']._serialized_end=139
  _globals['_CELLPOSESERVICE']._serialized_start=141
  _globals['_CELLPOSESERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
